### ISSUE TITLE
[tracking] Release 1.9

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1150]
* [ ] Documentation for agent changes #1092
* [ ] Merge UI upgrade #1143
* [ ] Prepare release notes

**Comment by pavolloffay** [comment]
This should be also included in 1.8 to avoid breaking changes https://github.com/jaegertracing/jaeger/pull/109

**Comment by pavolloffay** [comment]
Here is the milestone https://github.com/jaegertracing/jaeger/milestone/6

**Comment by yurishkuro** [comment]
> This should be also included in 1.8 to avoid breaking changes #109

are you referring to another repo? 109 here is from 2017

**Comment by pavolloffay** [comment]
The main missing parts are documentation of agent changes. @yurishkuro what documentation do you mean? The old flags are supported and deprecated.  The only reference in our docs is `--collector.host-port=jaeger-collector.jaeger-infra.svc:14267` which could be using a new flag.

Most importantly we should add ingester docs traced in https://github.com/jaegertracing/jaeger/issues/1030

**Comment by yurishkuro** [comment]
I meant to add notice of breaking changes in the changelog

**Comment by objectiser** [comment]
@yurishkuro Would it be possible to include https://github.com/jaegertracing/jaeger-ui/pull/263 in this release?

**Comment by pavolloffay** [comment]
https://github.com/jaegertracing/jaeger-ui/pull/263 will be added in 1.8.1 as discussed.
