### ISSUE TITLE
[tracking] Release 1.9

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1184]
Creating this to track release 1.9. Please post issue which we want to include in the release or point out breaking changes for documentation.

- [x] gRPC https://github.com/jaegertracing/jaeger/issues/773
- [ ] archive traces for Elasticsearch https://github.com/jaegertracing/jaeger/issues/818
- [x] Bump UI with trace graph
- [x] Bump jaeger lib to 2.0 - optional, jaeger go client has to be updated too

**Comment by yurishkuro** [comment]
We may need a smaller scope than #773, eg we don't have to block on not finishing up the JSON APIs.

**Comment by pavolloffay** [comment]
I mainly wanted to stabilize post spans service so we can start doing some work in clients. We can break it down into separate issues.

**Comment by objectiser** [comment]
@yurishkuro Would have been good to get https://github.com/jaegertracing/jaeger-ui/pull/276 in - but not sure how close it is.

**Comment by yurishkuro** [comment]
I'm fine either way. It only makes sense to bump it if we actually implement the metrics descriptions.

**Comment by objectiser** [comment]
Was hoping to have for 1.9 but should probably slip to 1.10 as would also need release of go client and resolve the Prometheus version

**Comment by pavolloffay** [comment]
thanks for the responses.

The main blocker is still https://github.com/jaegertracing/jaeger/issues/818. It would be great to get a review of that PR. 

So if the client is updated with the latest lib version before #818  is merged we can include, otherwise, do not block on it.

**Comment by pavolloffay** [comment]
We would like to release early on Monday. Before the release I will bump the UI @tiffon promised to release it before. 

The only outstanding issues are 
* #1284 
* #1197 (optional)

**Comment by yurishkuro** [comment]
#1283 needs to be added to the changelog
