### ISSUE TITLE
[tracking] Release 1.8.1

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1195]
The issue for tracking 1.8.1 release.

We need to cherry-pick the following commits:

- [x] metrics handler registration in agent https://github.com/jaegertracing/jaeger/commit/c296998c2e0491725033eb2ba8607c3d325856a3
- [x] agent flags https://github.com/jaegertracing/jaeger/issues/1192 https://github.com/jaegertracing/jaeger/commit/7d664e6b0af19ee8f60ecc488d8e42bb6fe65942
- [ ] UI bump with https://github.com/jaegertracing/jaeger-ui/pull/263

**Comment by pavolloffay** [comment]
Do we have any name requirements for branch name?  So far we don't have any maintenance branch. I am also wondering if the release will work from a branch other than master.

**Comment by yurishkuro** [comment]
1.8.x as name?

**Comment by tanuck** [comment]
Is there an ETA on this?

**Comment by pavolloffay** [comment]
Regarding the branch name.. I have talked to @objectiser we like `release-x.x`. It clearly distinguishes branch from the tag. It's also being used in other big projects k8s and istio for instance.

**Comment by pavolloffay** [comment]
I have pushed `release-1.8` Here is the comparison with master https://github.com/jaegertracing/jaeger/compare/release-1.8?expand=1 and CI https://travis-ci.org/jaegertracing/jaeger/builds/458738380

**Comment by pavolloffay** [comment]
The release build was successful. The images are re-tagged correctly
```
ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-agent:1.8 version                                                                                                         12:10 
Unable to find image 'jaegertracing/jaeger-agent:1.8' locally
1.8: Pulling from jaegertracing/jaeger-agent
Digest: sha256:7cc508a4d1b4508f6f74092322869342bab76c611fe141ed73bd7e1bd97d04a7
Status: Downloaded newer image for jaegertracing/jaeger-agent:1.8
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:01:37Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-agent:1.8.1 version                                                                                                       12:10 
Unable to find image 'jaegertracing/jaeger-agent:1.8.1' locally
1.8.1: Pulling from jaegertracing/jaeger-agent
Digest: sha256:7cc508a4d1b4508f6f74092322869342bab76c611fe141ed73bd7e1bd97d04a7
Status: Downloaded newer image for jaegertracing/jaeger-agent:1.8.1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:01:37Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-agent:1 version                                                                                                           12:10 
Unable to find image 'jaegertracing/jaeger-agent:1' locally
1: Pulling from jaegertracing/jaeger-agent
Digest: sha256:7cc508a4d1b4508f6f74092322869342bab76c611fe141ed73bd7e1bd97d04a7
Status: Downloaded newer image for jaegertracing/jaeger-agent:1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:01:37Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8                                                                                                                                                                     12:10 
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-query:1 version                                                                                                           12:10 
Unable to find image 'jaegertracing/jaeger-query:1' locally
1: Pulling from jaegertracing/jaeger-query
fdf780e5507a: Pull complete 
c1340a92107b: Pull complete 
Digest: sha256:321ca7c3d2d7bef8a56b50fae1cbf57c1fbf0a37829d969f79df376705349fcb
Status: Downloaded newer image for jaegertracing/jaeger-query:1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:02:16Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-query:1.8 version                                                                                                         12:10 
Unable to find image 'jaegertracing/jaeger-query:1.8' locally
1.8: Pulling from jaegertracing/jaeger-query
Digest: sha256:321ca7c3d2d7bef8a56b50fae1cbf57c1fbf0a37829d969f79df376705349fcb
Status: Downloaded newer image for jaegertracing/jaeger-query:1.8
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:02:16Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-query:1.8.1 version                                                                                                       12:10 
Unable to find image 'jaegertracing/jaeger-query:1.8.1' locally
1.8.1: Pulling from jaegertracing/jaeger-query
Digest: sha256:321ca7c3d2d7bef8a56b50fae1cbf57c1fbf0a37829d969f79df376705349fcb
Status: Downloaded newer image for jaegertracing/jaeger-query:1.8.1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:02:16Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-collector:1 version                                                                                                       12:10 
Unable to find image 'jaegertracing/jaeger-collector:1' locally
1: Pulling from jaegertracing/jaeger-collector
fdf780e5507a: Already exists 
9b59f889cb18: Pull complete 
Digest: sha256:e3d4db68822ef80fd2d86f365fcd9339139e114fa7e3605ff24ca915738bdbf9
Status: Downloaded newer image for jaegertracing/jaeger-collector:1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:02:08Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-collector:1.8 version                                                                                                     12:11 
Unable to find image 'jaegertracing/jaeger-collector:1.8' locally
1.8: Pulling from jaegertracing/jaeger-collector
Digest: sha256:e3d4db68822ef80fd2d86f365fcd9339139e114fa7e3605ff24ca915738bdbf9
Status: Downloaded newer image for jaegertracing/jaeger-collector:1.8
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:02:08Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/jaeger-collector:1.8.1 version                                                                                                   12:11 
Unable to find image 'jaegertracing/jaeger-collector:1.8.1' locally
1.8.1: Pulling from jaegertracing/jaeger-collector
Digest: sha256:e3d4db68822ef80fd2d86f365fcd9339139e114fa7e3605ff24ca915738bdbf9
Status: Downloaded newer image for jaegertracing/jaeger-collector:1.8.1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:02:08Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/all-in-one:1 version                                                                                                             12:11 
Unable to find image 'jaegertracing/all-in-one:1' locally
1: Pulling from jaegertracing/all-in-one
ff2da0ea7cbe: Pull complete 
534f6eaa0c9d: Pull complete 
Digest: sha256:87785ff5a909a0580405b8cfd48da501ea37d0bb83b541c768a7743adadbd5f6
Status: Downloaded newer image for jaegertracing/all-in-one:1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:00:22Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/all-in-one:1.8 version                                                                                                           12:11 
Unable to find image 'jaegertracing/all-in-one:1.8' locally
1.8: Pulling from jaegertracing/all-in-one
Digest: sha256:87785ff5a909a0580405b8cfd48da501ea37d0bb83b541c768a7743adadbd5f6
Status: Downloaded newer image for jaegertracing/all-in-one:1.8
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:00:22Z"}
 ploffay  ~/projects/golang/src/github.com/jaegertracing/jaeger   release-1.8  docker run --rm -it jaegertracing/all-in-one:1.8.1 version                                                                                                         12:11 
Unable to find image 'jaegertracing/all-in-one:1.8.1' locally
1.8.1: Pulling from jaegertracing/all-in-one
Digest: sha256:87785ff5a909a0580405b8cfd48da501ea37d0bb83b541c768a7743adadbd5f6
Status: Downloaded newer image for jaegertracing/all-in-one:1.8.1
{"gitCommit":"e24277e5edb8d4815f3dc06e70afbcaedc719534","GitVersion":"v1.8.1","BuildDate":"2018-11-23T11:00:22Z"}
```
