### ISSUE TITLE
Release 1.11 scope

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1343]
* [ ] make dependencies_v2 the default for Cassandra #1344
* [x] make gRPC reporter agent-collector default https://github.com/jaegertracing/jaeger/issues/1218
* [x] ES support TLS with credentials https://github.com/jaegertracing/jaeger/issues/1327

**Comment by pavolloffay** [comment]
If the gRPC works well I would like to cut the release the next week. Let's say on Monday/Tuesday.

**Comment by pavolloffay** [comment]
@tiffon what is the status of Jaeger UI? At the moment we depend on 1.0.0, I will update to 1.0.1 or do you want to release a new version with the latest fixes?

**Comment by tiffon** [comment]
@pavolloffay We'll cut a UI release for 1.11. Will report back here, when it's done. :+1:

**Comment by tiffon** [comment]
@pavolloffay We've released [Jaeger UI @ v1.1.0](https://github.com/jaegertracing/jaeger-ui/releases/tag/v1.1.0).

LMK if you need anything else.

**Comment by pavolloffay** [comment]
thanks @tiffon. I have updated it in the main repo.

**Comment by pavolloffay** [comment]
@yurishkuro what should be documented regarding the v2 schema?

**Comment by yurishkuro** [comment]
I think v2 now comes by default, and 1.10 changelog already provides migration steps
