### ISSUE TITLE
Jaeger clients should generate full-length trace/span IDs

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1657]
## Requirement - what kind of business use case are you trying to solve?

As a user, I should be able to use Trace/span IDs encoded in the trace context (e.g. `uber-trace-id` header) or exposed via `SpanContext.toTraceID()` methods to refer to traces in the UI.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently, many Jaeger clients drop leading zeroes from hex representation of trace/span IDs, resulting in inconsistent strings returned in JSON to the UI (relates to #1578). This is done as an optimization of the trace context header length, but it's a silly one since it only affects about 1/16th of all traces.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Client libraries should always output hex strings of 16 or 32 characters in length, depending on on whether 64bit or 128bit IDs are used, padded with zeros on the left to the desired length.

For backwards compatibility, clients should still be able to parse shorted hex strings.

* [x] Node.js client https://github.com/jaegertracing/jaeger-client-node/issues/391
* [x] Go client https://github.com/jaegertracing/jaeger-client-go/pull/472
* [x] Java client https://github.com/jaegertracing/jaeger-client-java/pull/746 (released in 1.5.0)
* [ ] Python client
* [x] C# client https://github.com/jaegertracing/jaeger-client-csharp/pull/171 (released in 0.4.0)
* [x] C++ client https://github.com/jaegertracing/jaeger-client-cpp/pull/259 (pending 0.7.0 release)

**Comment by SezalAgrawal** [comment]
Is this issue resolved?

**Comment by yurishkuro** [comment]
It is not, see the checklist in the description.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
