### ISSUE TITLE
Jaeger In-depth security

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1718]
In the [2019-05-04 Jaeger security audit](https://github.com/jaegertracing/security-audits/blob/master/SECURITY_AUDIT_2019_05_04.pdf), the auditors wrote:

> no actual security threats have been identified and only a handful of miscellaneous issues could be spotted.

However, the auditors were concerned with the lack of the actual security mechanisms:

> Everywhere in the codebase and in terms of key properties, a correct and complete configuration of the deployment and execution environment is a precondition and main approach. Such a complete reliance on perimeter-security calls the generally accepted industry practice of defense-in-depth into question.

This issue is a checklist of the existing security mechanisms in Jaeger, and any remaining gaps. It is broken into pairwise connections between Jaeger components.

Please refer to [Security page](https://www.jaegertracing.io/docs/latest/security/) in Jaeger documentation for instructions on securing Jaeger installation.

## Client to Agent

Agent is deprecated (#1718).

* [ ] ~UDP channels - no TLS/authentication~
* [x] HTTP config channel - #2249

## Client to Collector

* [x] HTTP - #2249
  * Note: some clients support passing auth-tokens or basic auth, that can be used if a reverse proxy is placed in front of collectors.
  * Blog post: [Secure architecture for Jaeger with Apache httpd reverse proxy on OpenShift](https://medium.com/@larsmilland01/secure-architecture-for-jaeger-with-apache-httpd-reverse-proxy-on-openshift-f31983fad400)

## Agent to Collector

Agent is deprecated (#1718).

* [x] gRPC - TLS with client cert authentication supported
  * Blog post: [Protecting the collection of spans (using Keycloak)](https://medium.com/jaegertracing/protecting-the-collection-of-spans-1948d88682e5)

## Collector/Query to Storage
* [x] Cassandra - TLS with client cert authentication supported; ~bearer token propagation~
* [x] Elasticsearch - TLS with client cert authentication supported; bearer token propagation
* [x] Kafka - Kerberos authentication supported

## Browser to UI
* [x] HTTP - TLS (#2249)
* [ ] HTTP - authentication (#4840)
  * Blog post: [Protecting Jaeger UI with an OAuth sidecar Proxy](https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1)

## Consumers to Query Service
* [x] HTTP - #2249
* [x] gRPC - #2248

**Comment by j771** [comment]
> Cassandra - TLS with client cert authentication supported; bearer token propagation
Is there any documentation/tutorials on this?
I am trying to secure connection between the Collector and Cassandra storage but have have not been able to successfully implement it.

**Comment by jpkrohling** [comment]
@rubenvp8510 is the bearer token propagation working already? I thought it hasn't been merged yet.

**Comment by jpkrohling** [comment]
Thanks for the info, @rubenvp8510. I changed the description to strike through the "bearer token propagation" in the Cassandra item (cc @j771).

**Comment by maestr0** [comment]
How to configure the Agent container to use TLS with client cert authentication? I'm running the Collector with mTLS. How do I tell the agent to use the client certs?

**Comment by yurishkuro** [comment]
Aren't these flags what you need?
```
$ go run ./cmd/agent help | grep tls
      --reporter.grpc.tls                                         Enable TLS when talking to the remote server(s)
      --reporter.grpc.tls.ca string                               Path to a TLS CA (Certification Authority) file used to verify the remote server(s) (by default will use the system truststore)
      --reporter.grpc.tls.cert string                             Path to a TLS Certificate file, used to identify this process to the remote server(s)
      --reporter.grpc.tls.key string                              Path to a TLS Private Key file, used to identify this process to the remote server(s)
      --reporter.grpc.tls.server-name string                      Override the TLS server name we expect in the certificate of the remove server(s)
```
