### ISSUE TITLE
Run client crossdock integration tests with all-in-one instead of Cassandra

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1762]
Client crossdock integration tests often fail because we have to wait too long for Cassandra, while specifically having a persistent storage is not relevant for those tests.

@Falco20019 wrote an awesome fix in jaegertracing/jaeger-client-csharp#152 to use all-in-one for all Jaeger backend components, which makes the test run much faster and hopefully more reliably. I've already applied that fix to Node.js client.

* [x] Node.js https://github.com/jaegertracing/jaeger-client-node/pull/375
* [x] Go https://github.com/jaegertracing/jaeger-client-go/pull/420
* [x] Java https://github.com/jaegertracing/jaeger-client-java/pull/654
* [x] Python https://github.com/jaegertracing/jaeger-client-python/pull/255

**Comment by yurishkuro** [comment]
It seems C++ client does not currently use crossdock, so this can be closed.
