### ISSUE TITLE
Converge on JAEGER_SAMPLING_ENDPOINT env variable for client's sampling

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1849]
## Update 2020-02-07 

per discussion https://github.com/jaegertracing/jaeger/issues/1971#issuecomment-570631770, we settled on the name `JAEGER_SAMPLING_ENDPOINT`. I'm adding the tracking:

* [x] Go client https://github.com/jaegertracing/jaeger-client-go/pull/511
* [ ] Java client
* [ ] Node client
* [ ] Python client
* [x] C# client https://github.com/jaegertracing/jaeger-client-csharp/pull/165
* [x] C++ client https://github.com/jaegertracing/jaeger-client-cpp/pull/200
* [ ] Documentation matrix update

## Original ticket

A bunch of tickets and PRs flying about, without a firm agreement on what we want to call this env variable.

Two candidates:
  1. `JAEGER_CONFIG_MANAGER_HOST_PORT` https://github.com/jaegertracing/jaeger-client-java/pull/554/files#r221994309
  1. `JAEGER_CONFIG_ENDPOINT` https://github.com/jaegertracing/jaeger-client-go/issues/282#issuecomment-537415291

Drawbacks:
  1. `JAEGER_CONFIG_MANAGER_HOST_PORT`: Does not allow http vs. https, which may be necessary/useful in some situations
  1. `JAEGER_CONFIG_ENDPOINT`: Consistent with JAEGER_ENDPOINT for submitting spans, but misleading, because JAEGER_ENDPOINT is the actual URL like `http://jaeger-collector:14268/api/traces`, but for configuration it's a _base url_ only, to be used with suffix endpoints like `/sampling` or `/baggage`

**Comment by yurishkuro** [comment]
cc @jpkrohling @pavolloffay

**Comment by jpkrohling** [comment]
I'm in favor of having a configuration option that accepts a URL, which contains all the components required to derive the actual endpoint value (protocol, host, port, base path).

The other obvious name for the property would be `JAEGER_CONFIG_URL`, but it has the same drawback as `JAEGER_CONFIG_ENDPOINT`, as it's not a complete URL (lacks the actual path). `JAEGER_CONFIG_BASE_URL` would be better in that sense, but I think it's unnecessarily verbose.

**Comment by pavolloffay** [comment]
`JAEGER_CONFIG_ENDPOINT`  is fine. First I didn't consider http/https problem.

Do we expect people using different endpoints? If no we could require specifying just the root path and set the base in the implementation to make it easier for users.

**Comment by yurishkuro** [comment]
Conclusion: go with `JAEGER_CONFIG_ENDPOINT`, but make it explicit in the description that this is a "base URL".

Agreed?

**Comment by yurishkuro** [comment]
Update: per discussion https://github.com/jaegertracing/jaeger/issues/1971#issuecomment-570631770, we settled on the name `JAEGER_SAMPLING_ENDPOINT`

**Comment by Falco20019** [comment]
C# can be checked as done as it's merged and released as of `0.3.7`.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
