### ISSUE TITLE
Add a MAINTAINERS/CODEOWNERS file

### ISSUE THREAD

**Issue by caniszczyk** [jaegertracing/jaeger#254]
It would be great if the maintainers were listed via a file. GitHub now actually has support for something called "CODEOWNERS" which should work: https://help.github.com/articles/about-codeowners/

cc: @yurishkuro

**Comment by yurishkuro** [comment]
* [ ] uber/jaeger https://github.com/uber/jaeger/commit/358138444457ba228eb08cce9994963f75b559f3
 * [ ] uber/jaeger-ui
 * [ ] uber/jaeger-lib
 * [ ] uber/jaeger-client-go
 * [ ] uber/jaeger-client-java
 * [ ] uber/jaeger-client-python
 * [ ] uber/jaeger-client-node

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients, so this is done for other repos
