### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2600]
Since yesterday our PRs are taking forever to run CI because there is just a single executor running across all of them.

Apparently, we need to migrate to travis-ci.com, and they did not do it automatically.

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

* [x] check that all repos are able to build - this seems fine now
* [x] ~copy secrets where necessary~ - done by travis migration automatically, thankfully
* [ ] update the build badges in READMEs (https://github.com/search?q=org%3Ajaegertracing+travis-ci.org&type=code)
* [ ] update branch protections to require .com instead of .org builds

**Comment by jpkrohling** [comment]
I can take care of it tomorrow, if you haven't yet.

**Comment by yurishkuro** [comment]
I migrated all repos, but we may have to go and re-define secrets, doesn't seem like they are moved during migration.

master build is now running 5 jobs: https://travis-ci.com/github/jaegertracing/jaeger/builds/195053976

**Comment by jpkrohling** [comment]
Longer term, we should consider moving some (or all) of the jobs to GitHub Actions.

**Comment by yurishkuro** [comment]
Maybe. Chris said GH Actions have 60 parallel runners per org, compared to 5 in Travis.

**Comment by yurishkuro** [comment]
Update: the travis-ci.com builds are now required instead of travis-ci.org, however I see they keep failing on the unit test stage. For some reason the test command, according to travis, does not produce any output for 10min and it kills the job. I added `travis_wait` in #2598, yet to see if it helps (a run still fail for another odd reason), but it's far from ideal because it swallows all output, so if our tests run for 15min, we won't see anything in the logs until the test run is fully finished.

**Comment by yurishkuro** [comment]
As far as I can tell, it keeps failing due to #2601.

**Comment by yurishkuro** [comment]
Changed to a tracking issue, because we need to make sure all SDK repos are able to build. And we need to copy over the secrets.

**Comment by jpkrohling** [comment]
I can take a look, but I noticed that there's something weird already with the first repo I tried: jaeger-client-node. Did you migrate all repos already? In travis.com , I triggered a build for master, but looks like it doesn't see the right commit for "master":

![image](https://user-images.githubusercontent.com/13387/97545667-a0194c00-19cb-11eb-8923-3e9b2ed52048.png)


![image](https://user-images.githubusercontent.com/13387/97545739-b3c4b280-19cb-11eb-84bc-cd3f16b0a437.png)

**Comment by yurishkuro** [comment]
We should try with a new commit. Some of Jaeger projects used to run on travis-ci.com in the past, so we can see the old build history. But I would've expected master build to work.

**Comment by yurishkuro** [comment]
I think I migrated all repos, but we also need to change their branch protections to require .com builds instead of .org.

And we need to update build badges in the READMEs: https://github.com/search?q=org%3Ajaegertracing+travis-ci.org&type=code

**Comment by cwsolee** [comment]
Just fyi, Travis post some updates here too https://blog.travis-ci.com/oss-announcement

**Comment by yurishkuro** [comment]
Superseded by #2645 - migrating to GitHub Actions.
