### ISSUE TITLE
[meta] Migrate from Travis to GitHub actions

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2691]
Split from https://github.com/jaegertracing/jaeger/issues/2645 to track the work in other repos:

  * [x] jaeger-lib https://github.com/jaegertracing/jaeger-lib/issues/85
  * [x] jaeged-idl https://github.com/jaegertracing/jaeger-idl/pull/68
  * [x] jaeger-operator
  * [x] jaeger-client-java https://github.com/jaegertracing/jaeger-client-java/issues/765
  * [x] jaeger-client-go https://github.com/jaegertracing/jaeger-client-go/issues/554
  * [x] jaeger-client-python https://github.com/jaegertracing/jaeger-client-python/issues/295
  * [x] jaeger-client-node https://github.com/jaegertracing/jaeger-client-node/issues/452
  * [x] jaeger-client-cpp https://github.com/jaegertracing/jaeger-client-cpp/issues/256
  * [x] jaeger-client-csharp (uses AppVoyer, does not need to migrate)
  * [x] docker-protobuf (does not use Travis)
  * [x] docker-thrift (does not use Travis)
  * [ ] spark-dependencies
  * [x] jaeger-analytics-java
  * [ ] jaeger-performance
  * [ ] jaeger-analytics-flink
  * [ ] https://github.com/jaegertracing/xdock-zipkin-brave
  * [ ] https://github.com/jaegertracing/legacy-client-java
