### ISSUE TITLE
When to release 1.22

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2734]
* [x] #2048 Add support for Elasticsearch ILM Polices
  * [x] #2738 Remove deprecated CLI flags
  * [x] #2645 & #2810 GitHub Actions for release process
  * [x] #2337 TLS support for HTTP API of Query server 
  * [ ] ~~#2781 Remove temporary usage of a personal Thrift fork~~

**Comment by yurishkuro** [comment]
The only two open PRs that might be interesting to add are these:
  * #2454 Add support for Elasticsearch ILM Polices 
  * #2337 TLS support for HTTP API of Query server  (approved)

**Comment by jpkrohling** [comment]
I was kinda expecting to release a version bump fixing the Thrift issue for the agent. Do you think it would be worth forking Thrift for the time being, so that we can tag our fork to be able to use the fix?

**Comment by jpkrohling** [comment]
Also, we have a couple of things in the milestone: https://github.com/jaegertracing/jaeger/milestone/16

**Comment by yurishkuro** [comment]
> Do you think it would be worth forking Thrift for the time being, so that we can tag our fork to be able to use the fix?

perhaps. Not sure how much work it is.

**Comment by jpkrohling** [comment]
I might be wrong, but I think it's just a matter of forking/tagging for the Go library. I can try to schedule some time to experiment with this.

**Comment by yurishkuro** [comment]
Added #2645

**Comment by jpkrohling** [comment]
I think we are ready for the release. Following the tradition, the newly appointed maintainer is invited to perform the release ;-)

**Comment by albertteoh** [comment]
I would be honoured, working on it now

**Comment by albertteoh** [comment]
I'm planning to tag a jaeger-ui release, but master builds are failing due to a license scan check. I'm looking into the license scan error, but unable to proceed identifying the problematic file as I'm not a maintainer it seems:

<img width="775" alt="Screen Shot 2021-02-19 at 2 41 22 pm" src="https://user-images.githubusercontent.com/26584478/108454644-d18e8e00-72c0-11eb-9172-f1a29525479e.png">

Is someone able to help with this or can the license check be ignored and proceed with the release tag?

**Comment by yurishkuro** [comment]
Link? I can check access.

**Comment by albertteoh** [comment]
> Link? I can check access.

Thanks @yurishkuro. [Here's the link](https://app.fossa.com/projects/git%2Bgithub.com%2Fjaegertracing%2Fjaeger-ui/refs/branch/master/483d2286bfc4430025e1c11f98813fddf266f790).

For context, I got there by going to https://github.com/jaegertracing/jaeger-ui, and clicking on the red "X", then clicking on the license check failed build.

**Comment by yurishkuro** [comment]
I don't have access either!

**Comment by yurishkuro** [comment]
I sent email to FOSSA support.

I don't think this is a new issue though, we can probably ignore it. Most likely the warning is coming from some build-time dependencies.

**Comment by yurishkuro** [comment]
btw,  would prefer to do the UI release without merging all those dependabot upgrades, I think they need a round of sanity check testing of the UI (unfortunately, unit tests do not fully cover UI).

**Comment by albertteoh** [comment]
okay, noted; would you like me to revert those last two merges I did (a minutes ago) or just not merge dependabot upgrades going forward?

**Comment by jpkrohling** [comment]
Let's hold it until next Tuesday morning (your timezone, @albertteoh). I can do some manual testing on Monday.

**Comment by albertteoh** [comment]
Sounds good, @jpkrohling, I'll wait till Tuesday. I did perform some (basic) manual testing and things seemed fine so far, though I'm sure there are a number of features that I'm not familiar with.

On a related note, if this is something we'll need to do each time before tagging a new UI release, do you think we ought to have a document outlining manual sanity testing steps until we have enough confidence in our unit tests? Or maybe even invest in an automated UI testing framework like selenium?

**Comment by jpkrohling** [comment]
> do you think we ought to have a document outlining manual sanity testing steps until we have enough confidence in our unit tests?

Absolutely, I was thinking about recording a BDD-style set of tests as I go through it this morning, but I might not have enough time. Feel free to suggest an initial set of tests, I can certainly help to review it!

**Comment by jpkrohling** [comment]
I just tried the latest master branches (d9453e08a9683cca90e198db62768fe78dd1f9af and jaegertracing/jaeger-ui@35cc879f816eec15efa16e1981b542555db3c057) and it looks fine to me. One thing that I would like to get in before the release is the jaegertracing/jaeger-ui#702, as it fixes a CVE that was reported to me last week.

**Comment by albertteoh** [comment]
Thanks @jpkrohling, I noticed https://github.com/jaegertracing/jaeger-ui/pull/702 is merged now so I'll go head with tagging jaeger-ui, then create the PR for jaeger release v1.22.0.

**Comment by albertteoh** [comment]
> > do you think we ought to have a document outlining manual sanity testing steps until we have enough confidence in our unit tests?
> 
> Absolutely, I was thinking about recording a BDD-style set of tests as I go through it this morning, but I might not have enough time. Feel free to suggest an initial set of tests, I can certainly help to review it!

Cool, I've created an issue for this: https://github.com/jaegertracing/jaeger-ui/issues/708.
