### ISSUE TITLE
Replace the use of "esc" with standard "embed" package

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2749]
We're currently using `github.com/mjibson/esc` to embed certain files (like UI assets) into binaries.

Upcoming Go 1.16 supports this with a new standard package [embed](https://tip.golang.org/pkg/embed/) and `//go:embed` directive.

* [x] investigate what it would take to switch to `embed` #2835
* [x] embed HotROD assets #2835
* [x] embed Elasticsearch mappings #2822
* [x] embed UI assets (NB: we should investigate the impact on binary size compared to the current `esc` embedding. Maybe consider compressing the assets)
  * [x] placeholder index.html #2846
  * [x] actual UI #3399

See also: #2748

**Comment by yurishkuro** [comment]
A blog post that might be useful (I did not read it yet): https://lakefs.io/working-with-embed-in-go/

**Comment by lonewolf3739** [comment]
@yurishkuro I would like to work on this.

**Comment by yurishkuro** [comment]
+1
