### ISSUE TITLE
"Monitor" tab for service health metrics

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2954]
### Jaeger-Query

Owners: @albertteoh 

- [x] #2946: Add metrics query API spec
- [x] #2977: Add Metrics Reader interface
- [x] #2983, #2988, #3004: Add M3 reader implementation
- [x] #3049: Add factory and flags
- [x] #3055: Add TLS support
- [x] #3091: Add GRPC handler
- [x] #3095: Add HTTP handler
- [x] #3060, #3061: Update query service
- [x] #3079: Hookup metrics query to "main"
- [x] #3171: [Explore options to make monitor tab work for all-in-one (or create issue)](https://github.com/jaegertracing/jaeger/issues/3107)

### Jaeger-UI

Owners: @th3M1ke 

- [x] Approve UX & UI design (this issue)
- [x] https://github.com/jaegertracing/jaeger-ui/pull/815: Create Monitoring Tab for Jaeger UI

### Documentation

Owners: @albertteoh 

- [x] https://github.com/jaegertracing/documentation/pull/539: Add usage documentation for metrics query API (noting that this is "experimental")
- [x] https://github.com/jaegertracing/documentation/issues/553: Add usage documentation for Monitor tab UI

## Requirement - what kind of business use case are you trying to solve?
The main proposal is documented in: https://github.com/jaegertracing/jaeger/issues/2736.

The motivation is to help identify interesting traces (high qps, slow or erroneous) without knowing the service or operations up-front. 

Use cases include:
- Post deployment sanity checks across the org, or on known dependent services in the request chain.
- Monitoring and root-causing when alerted of an issue.
- Better onboarding experience for new users of Jaeger UI.
- Long-term trend analysis of QPS, errors and latencies.
- Capacity planning.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a new "Monitoring" tab situated after "Compare" containing service-level request rates, error rates, latency and impact (= `latency * request rate` to avoid "false positives" from low QPS endpoints with high latencies). 

The data will be sourced from [jaeger-query's new metrics endpoints](https://github.com/jaegertracing/jaeger/issues/2736).

As the jaeger-query metrics endpoints require opt-in to be enabled, the Monitor tab will have a sensible empty state, perhaps a link to documentation on how to enable metrics querying capabilities.

### Workflow
The screen will open to a per-service level set of metrics sorted, by default, on Impact. Columns are configurable by the user with other latency percentiles available, among others. A search box will be available to filter on service names. 

The user need only supply the time period to fetch metrics on (similar to Find Traces), defaulting to a 1 hour lookback.

Note the user is not required to define the step size (the period between data points), at least in this iteration, to keep the user experience as simple as possible. Instead we propose to define the step size based on a sensible heuristic based on the query period and/or the width of the chart. For example:
- `< 30m` search period -> 15s step
- `< 1h` search period -> 1m step, etc.

There are two possible actions from here in this tab:
- Click on a service to drill down to per-operation metrics.
- Click on "View all traces" to go to the Search tab with the service pre-populated and Operation filter set to "all".

#### Service metrics page
If drilling down into the service-level metrics, the page will show a summary of the RED metrics at the top along with the per-operation equivalent metrics as with the per-service metrics above. Also similarly, there will be a search box to filter on operations, and the user has the option to "View all traces" for a given operation.

#### Search tab
The search tab will be the final stage in the workflow (except of course if going back to a previous state), which is pre-populated with the service and/or operation as well as the search period. 

The search period will be sticky between each of these screens to maintain consistency in search results.

### Demo

Courtesy of @Danafrid.

![jaeger-monitor-tab-service](https://user-images.githubusercontent.com/26584478/114831799-20fcc080-9e11-11eb-9df6-5eed4ca2d1ec.jpg)

![jaeger-monitor-operation-tab](https://user-images.githubusercontent.com/26584478/114831774-19d5b280-9e11-11eb-9e69-95de1859a91e.jpg)

https://user-images.githubusercontent.com/26584478/114826556-fad42200-9e0a-11eb-92b5-6454a51f8863.mov

## Any open questions to address

- Any suggestions on charting libraries use for the larger detailed charts and the smaller row-level graphs in the table views?
- Any requirement to maintain consistency with the trace statistics table view?
- What is the preferred behaviour when a large number of services/operations are returned?
  - Show the top n results ordered by Impact by default? What if the user sorts on a different metric like errors? Just sort on the current n results or refetch from jaeger-query?
  - Show everything?
  - Paginate? (probably want to avoid this as it would require maintaining state in UI or jaeger-query)

**Comment by jpkrohling** [comment]
I love these mockups, and I can think of a couple of things to add after this is implemented. For instance, clicking on a part of the graph could lead people to the search results view for the relevant part they clicked. For instance, when clicking in the most recent part of the errors graph, the search results for "error=true" would be shown for the time window representing the area in the graph that the user clicked. Same for latency, returning the traces for that time window, sorted by latency, with the highest first.

In any case, I would recommend taking a look at Kiali, to see what they've done and what we could replicate. I particularly love the flame graphs, which should give an idea of how normal the latencies are for a given service/endpoint.

![image](https://user-images.githubusercontent.com/13387/116046028-f3b2dc80-a672-11eb-9675-595a9781cd27.png)

![image](https://user-images.githubusercontent.com/13387/116045953-de3db280-a672-11eb-8d60-36e41ce89dc6.png)

The images are from this blog post: [Trace my mesh](https://medium.com/kialiproject/trace-my-mesh-part-1-3-35e252f9c6a9). Make sure to check the [part 2](https://medium.com/kialiproject/trace-my-mesh-part-2-3-13cd6ccae1de) and [part 3](https://medium.com/kialiproject/trace-my-mesh-part-3-3-e1e64795e61f) too.

>Any suggestions on charting libraries use for the larger detailed charts and the smaller row-level graphs in the table views?

I asked the Kiali folks to chime in, I'm sure they have some experience with this. In any case, I would ask to keep one feature in mind: the ability to embed those graphs by other solutions. I'd argue that a key aspect of the Jaeger UI is the fact that portions of it can be embedded into other applications, such as Kiali and Grafana Tempo.

>Any suggestions on charting libraries use for the larger detailed charts and the smaller row-level graphs in the table views?

I would vote for the most conservative solution that pleases the biggest number of use cases. This is a new feature, we don't need to get it 100% right on our first try.  I think sorting by the biggest impact would be the best solution.

>What if the user sorts on a different metric like errors? Just sort on the current n results or refetch from jaeger-query?

Re-fetch.

>Paginate? (probably want to avoid this as it would require maintaining state in UI or jaeger-query)

Can't we do an infinite scroll? The UI would then run the same query, for the same time window, just with a different offset.

**Comment by th3M1ke** [comment]
@yurishkuro @albertteoh Could I take the UI tasks on?

**Comment by albertteoh** [comment]
@th3M1ke yup, I've added you as an owner of the UI tasks. Thanks for your help!

**Comment by RyanSiu1995** [comment]
Hi @albertteoh , anything can need the folks to make this released faster?
I can pick some if you have that.

**Comment by albertteoh** [comment]
@th3M1ke / @yoave23 how are you guys going with the UI side of the Monitor tab? Are there any well-defined/self-contained tasks that @RyanSiu1995 could help with?

I'll also need to complete the documentation but didn't want to work on that until the UI component is ready to avoid prematurely communicating the completion of this feature.

**Comment by th3M1ke** [comment]
Hi folks! We are about to finish. Covering features with tests.  Hope will open PR by the end of this week

**Comment by RyanSiu1995** [comment]
Thank you! Hope that it can come alive soon.

**Comment by albertteoh** [comment]
> May I ask why the demand for #2954 has not been online yet?

@tianruyun We're still testing this feature; resulting in some identified bugs/improvements either in OpenTelemetry collector (data from which the Monitor tab depends on) or Jaeger:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6935: OpenTelemetry collector's prometheus exporter bug leading to a counter value overflow on metrics expiration.
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7149: OpenTelemetry collector's prometheus remote write exporter crashes on metrics expiration.
- https://github.com/jaegertracing/jaeger/issues/3522: Support duration strings for duration query parameters: `lookback`, `ratePer` and `step`.
- https://github.com/jaegertracing/jaeger-ui/issues/879: The rate duration defaults to `1 hr` leading to low call rates if there's a short sample size of metrics, which can be a bit confusing. An easy fix is to change this to `10m` to start with.

Those are the last remaining tasks so far before we can make this feature available in Jaeger. I plan to find some time to work on documentation in parallel with the remaining two Jaeger tasks above. You're most welcome to provide contributions as well. 😄

**Comment by schickling** [comment]
Really excited for this. Is there a way to already give this a try on the latest release?

**Comment by albertteoh** [comment]
@schickling there's demo you can run locally in: https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor.

**Comment by albertteoh** [comment]
All tasks complete, closing this issue. We can address any feedback/bugs as separate Issues/PRs.

**Comment by FingerLiu** [comment]
Waiting to use in production! When will this release?

**Comment by albertteoh** [comment]
> Waiting to use in production! When will this release?

Next release planned for 6 April: https://github.com/jaegertracing/jaeger/blob/main/RELEASE.md#release-managers

**Comment by FingerLiu** [comment]
Hi @albertteoh  it seems that Monitor Tab still not in the new release 1.33 https://github.com/jaegertracing/jaeger/releases/tag/v1.33.0

What obstacle did we met?

**Comment by albertteoh** [comment]
@FingerLiu most of the functionality for Monitor Tab were essentially completed in previous releases which is why you couldn't see references to Monitor Tab in the [jaeger v1.33.0 release notes](https://github.com/jaegertracing/jaeger/releases/tag/v1.33.0).

Most of the remaining changes needed to consider the Monitor Tab work "done" were [documentation](https://www.jaegertracing.io/docs/1.33/spm/) and [frontend bug fixes](https://github.com/jaegertracing/jaeger-ui/blob/main/CHANGELOG.md#v1220-2022-04-11), which were both released together as part of the [jaeger v1.33.0 release](https://github.com/jaegertracing/jaeger/releases/tag/v1.33.0) (NB: I've updated these release notes to include the pinned Jaeger UI version).
