### ISSUE TITLE
Upgrade to Go 1.18

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3622]
* [x] upgrade mockery #3621 
* [x] fix typecheck linter #3624
  * Related https://github.com/golangci/golangci-lint/issues/2649
* [x] upgrade CI files #3624
* [x] go.mod, Docker, etc. #3626

**Comment by yurishkuro** [comment]
Forgot go.mod
