### ISSUE TITLE
Remove dependency on jaeger-lib

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3766]
There are several issues with the dependency on jaeger-lib:
  * it is shared with jaeger-client-go, which is now deprecated, so the library does not need to be standalone
  * library does not use go modules, migrating it to `go mod` is non-trivial because it's already v2
  * because it cannot be migrated to go modules, it cannot be upgraded to later versions of go-kit. The older 0.11 version of go-kit has dependencies with known vulnerabilities
  * there's not much need to depend on go-kit in the first place, we're only using it for its expvar package, which is relatively trivial to implement (especially without the histograms)

There are two directions we can take:
  1. migrate to OpenTelemetry instead. This is preferable, but will involve non-trivial amount of work. Good news is that work can likely be done piecemeal.
  2. Keep using jaeger-lib API for metrics and pull it inside this repo as `internal`.
    * unfortunately, this does not fully remove dependency on jaeger-lib because we're still using jaeger-client-go (cf. #3381, #3380)
  3. Keep using jaeger-lib API for metrics but implement it with OpenTelemetry SDK. This seems like the least resistance path (need to prototype it to test viability).

(Update 2023-01-29) Current plan:
  * [x] Clone jaeger-lib into Jaeger repo (done in #3767, #3772)
  * [x] Upgrade HotROD to use OTEL SDK (via OT bridge), which removes the need for uber/jaeger-lib (done in #4187)
  * [x] Upgrade tracegen to use OTEL SDK (done in #4189)
  * [x] Upgrade collector/query/all-in-one to use OTEL SDK (via OT bridge)
  * [x] Fix crossdock (maybe we don't need SDK testing there anymore)
