### ISSUE TITLE
(deprecation) Remove jaeger-agent

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4739]
`jaeger-agent` used to be very useful when Jaeger SDKs were in active use with their default UDP-based exporters. Most OTEL SDKs do not support UDP exporter and are phasing out Jaeger exporters altogether. That makes `jaeger-agent` an unnecessary component since it is only designed to receive data via UDP.

Note that having a host-local agent is still an often desirable deployment model, because it simplifies the SDK configuration (SDK only needs to know localhost:port address). However, OTEL Collector is a more suitable component for a host agent now, especially since it can also serve other functions like logs forwarding, not just trace data proxying.

## Migration

See https://www.jaegertracing.io/docs/latest/architecture/ for the recommended deployment configurations.

## Proposal

Deprecate `jaeger-agent` and in 6-months remove it from the code base. This will allow removing a large chunk of code that we won't need to maintain anymore.

* [x] add deprecation warnings to the binary, the docs, and Docker Hub repo
  * #4749
  * https://github.com/jaegertracing/documentation/pull/656
* [x] wait for 6 months
* [x] remove agent from the build pipeline #6081
* [x] mark Docker Hub repo as archived
* [x] remove agent from Helm chart and k8s operator
  * [ ] https://github.com/jaegertracing/helm-charts/issues/607
  * [ ] https://github.com/jaegertracing/jaeger-operator/issues/2714
* [x] remove mentioning of the agent from the docs and diagrams https://github.com/jaegertracing/documentation/pull/757
* [x] remove imports of jaeger code from otel contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35765
* [x] remove the code for the agent #6868
* [x] clean up IDLs https://github.com/jaegertracing/jaeger-idl/pull/157

### Accept OTLP

We could deprecate UDP receivers in the agent and instead mount an OTLP receiver. This will allow `jaeger-agent` to continue to exist close to its current form. But the benefits of doing so are unclear, while the downsides are that we still need to support a chunk of source code and it creates/causes confusion with the users if the agent is required and why.

**Comment by yurishkuro** [comment]
cc @vprithvi @jaegertracing/jaeger-maintainers @jaegertracing/helm-charts-maintainers

**Comment by vprithvi** [comment]
Thanks for the heads up! Agree with this direction (also, goodbye 64KB UDP packet size limitation)

**Comment by James-Bartman** [comment]
I'm using the jaeger agent pipeline and have tried moving to the OTLP pipeline, but I am running into a host of issues. The opentelemetry-otlp pipeline doesn't support batching with Tokio, has a wierd Config conflict, and more. Are there any examples of how to switch over without running into all of these issues?

**Comment by yurishkuro** [comment]
@James-Bartman jaeger-agent does not provide any batching, it is a pass-through proxy. If you are using the classic Jaeger SDKs, they typically would batch spans in the app's memory and export a batch to the backend. You can reconfigure them to export to collector and bypass the agent. Unless your specific SDK does not support non-UDP exports - I don't know since Rust was not officially supported by Jaeger team. The OTEL version does support batching, and can talk to collector: https://docs.rs/opentelemetry-jaeger/latest/opentelemetry_jaeger/

**Comment by James-Bartman** [comment]
@yurishkuro Thank you! I was able to get implement the `opentelemetry_otlp` exporter using `tonic`, and then I passed it into my `opentelemetry_otlp` pipeline with `Tokio` batching. There are a lot of conflicting examples on the web, but the docs you linked a bit of elbow grease got it all working.

**Comment by mrasap** [comment]
Thanks for the heads up! Is it already possible to disable the agent when running the `jaeger-operator` with a `jaeger` CR using `strategy: production`?

The docs currently suggest not to use the agent because it is deprecated, but the configuration does not seem to allow this. 

I have installed the `jaeger-operator` through the helm chart (`v1.49.0`), using `image.tag=1.52.0`.

**Comment by yurishkuro** [comment]
@mrasap good question, this should be part of the deprecation plan. I don't know the answer, so asked here: https://github.com/jaegertracing/jaeger-operator/issues/2401

**Comment by varshith257** [comment]
@yurishkuro It's time to mark the second point in the checklist of ticket. It's been 6+ months

**Comment by chinaran** [comment]
https://github.com/jaegertracing/jaeger-operator/pull/2611
The PR for jaeger agent deprecation was Revert.
May I ask if it should be added back?

**Comment by yurishkuro** [comment]
@chinaran yes we should remove it from the operator, but the description lists the order in which the steps need to be done.

**Comment by chinaran** [comment]
> [@chinaran](https://github.com/chinaran) yes we should remove it from the operator, but the description lists the order in which the steps need to be done.

I understand, thanks.

**Comment by yurishkuro** [comment]
Completed!
