### ISSUE TITLE
feat: Jaeger v2 based on OpenTelemetry collector

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4843]
Proposal: https://docs.google.com/document/d/1s4_6VgAS7qAVp6iEm5KYvpiGw3h2Ja5T5HpKo29iv00/view

This replaces the previous attempt: #3500.

### Proof of concept

* [x] A single binary with memory storage and all-in-one functionality #4766
* [ ] Validate that the current storage configuration works for primary / archive storage.
* [ ] Default configuration solution (do not require config file for all-in-one) #4842
* [ ] Demonstrate Kafka exporter / receiver (ideally from OTEL), compatible with existing Jaeger Kafka writer
* [ ] Define v2 storage API that operates on OTLP batches, see if internal & remote APIs can be identical

### Feature parity

* [ ] Extend configuration of `jaeger_storage_exporter` to support all existing backends
* [ ] Metrics
* [ ] Traces
* [ ] What to do with admin port / services
* [ ] Adaptive sampling processor

### Prepare for Beta

* [ ] Add to integration tests
* [ ] Add to release pipeline
* [ ] Documentation

### Prepare for GA

* [ ] Helm chart
* [ ] Operator
* [ ] Clarify https://github.com/jaegertracing/jaeger#version-compatibility-guarantees 

### Enhancements

* [ ] SPM built-in
* [ ] Integrate with OTEL collector builder `ocb`
* [ ] Print active configuration (unresolved: [Print final configuration OTEL #1791](https://github.com/open-telemetry/opentelemetry-collector/issues/1791)), https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27003

**Comment by pavolloffay** [comment]
The V2 is as well affected by https://github.com/open-telemetry/opentelemetry-collector/pull/8768, It can cause startup failure.

**Comment by yurishkuro** [comment]
The new `jaeger` binary is available as Docker image https://hub.docker.com/repository/docker/jaegertracing/jaeger/tags

**Comment by yurishkuro** [comment]
I wrote down some thoughts on what [Jaeger Storage API v2 might look like](https://docs.google.com/document/d/1s4_6VgAS7qAVp6iEm5KYvpiGw3h2Ja5T5HpKo29iv00/edit#heading=h.hlhu8pegwdcj). Interested in feedback.

**Comment by hdost** [comment]
> I wrote down some thoughts on what [Jaeger Storage API v2 might look like](https://docs.google.com/document/d/1s4_6VgAS7qAVp6iEm5KYvpiGw3h2Ja5T5HpKo29iv00/edit#heading=h.hlhu8pegwdcj). Interested in feedback.

So one thing that I think might be worth thinking about as well is search complexity. One issue I know we had was making search efficient on large span storage. 
Time range to limit is useful, but painful for users. Being able to search on attributes is a must. It might be good add criteria to compare about query patterns as well.

**Comment by 88vishnu** [comment]
Appx by when Jaeger-v2 will be available with tail-based-sampling??

**Comment by yurishkuro** [comment]
I am hoping to make good progress on v2 in the Spring if we get 3 interns, and then in the summer to get it to GA.

**Comment by yasharne** [comment]
Is this open to contributing? if yes, where can I find the open tasks/issues?

**Comment by yurishkuro** [comment]
@yasharne it is definitely open, but I'd say most open issues here are medium complexity, not `good-first-issue`. The open issues are listed in this ticket (and more in Google docs).

**Comment by tmeckel** [comment]
When I try to use the OLTPLogExporter with Jeager and GRPC,

```python
get_logger_provider().add_log_record_processor(
    BatchLogRecordProcessor(
        exporter=OTLPLogExporter(
            endpoint="http://jaeger:4317",
            insecure=True,
        ),
    )
)
```

I recieve the following error:

```
2024-02-27 13:41:34,233 ERROR [opentelemetry.exporter.otlp.proto.grpc.exporter] [exporter.py:306] - Failed to export logs to jaeger:4317, error code: StatusCode.UNIMPLEMENTED
```

An indication that https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/logs/v1/logs_service.proto is not implemented by Jaeger. Is this correct? Or did I configured Jaeger incorrectly, ref. to following Docker Compose snippet (ports 4317 and 4318 are used only internally using the network `ipam`)?

```yaml
---
# This is a Docker Compose override file to add jeager tracing
version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - ipam

  network-managemnent:
    depends_on:
      - jaeger
```

https://github.com/open-telemetry/opentelemetry-collector/issues/6363

**Comment by yurishkuro** [comment]
@tmeckel  Jaeger is not a logging backend, it only accepts traces.

**Comment by adriangb** [comment]
> [@tmeckel](https://github.com/tmeckel) Jaeger is not a logging backend, it only accepts traces.

We run a backend that used to only accept traces (we now accept OTEL logs) but until Logs were more stable and widely used we sent zero-duration traces to model point in time events. I was curious how Jaeger behaves if you send it zero duration traces as a way to transmit point in time information, it seems to have no issues accepting or displaying the data:

<img width="1783" alt="Image" src="https://github.com/user-attachments/assets/0de27a36-81dd-445a-870b-388902ed92cd" />

Here's how I generated this data:

<details>
<summary>Python example</summary>

```python
#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
# "opentelemetry-api==1.29.0",
# "opentelemetry-sdk==1.29.0",
# "opentelemetry-exporter-otlp==1.29.0",
# ]
# ///

from collections.abc import Iterator
from contextlib import contextmanager
from time import sleep, time_ns
from typing import Any

from opentelemetry import context, trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import SimpleSpanProcessor
from opentelemetry.util import types


# Users don't writ this class, I'm proposing we add the methods to the existing Tracer class.
class LoggingTracer(trace.Tracer):
    def __init__(self, inner: trace.Tracer):
        self._inner = inner
        self.start_span = inner.start_span
        self.start_as_current_span = inner.start_as_current_span

    def warn(
        self,
        event_name: str,
        context: context.Context | None = None,
        attributes: types.Attributes | None = None,
    ) -> None:
        attributes = dict(attributes or {})
        attributes['verbosity'] = 'warn'
        time = time_ns()
        span = self._inner.start_span(
            name=event_name,
            context=context,
            attributes=attributes,
            start_time=time,
        )
        span.end(time)

    def start_span(self, *args: Any, **kwargs: Any) -> trace.Span:
        return self._inner.start_span(*args, **kwargs)

    @contextmanager
    def start_as_current_span(  # type: ignore  # implementing a Tracer requires access to private APIs. Why?
        self, *args: Any, **kwargs: Any
    ) -> Iterator[trace.Span]:
        return self._inner.start_as_current_span(*args, **kwargs)  # type: ignore  # Same as above


provider = TracerProvider()
processor = SimpleSpanProcessor(
    OTLPSpanExporter(
        endpoint='localhost:4317',
        insecure=True,
    )
)
provider.add_span_processor(processor)

trace.set_tracer_provider(provider)

tracer = trace.get_tracer('my.tracer.name')

tracer = LoggingTracer(tracer)

# with context
with tracer.start_as_current_span('outie') as span:
    sleep(0.1)
    tracer.warn('inne')

# with no context
tracer.warn('contextless')
```

</details>
