### ISSUE TITLE
[jaeger-v2] Rethink components configuration to align with OTEL

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5229]
Right now several PRs that are trying to add support for standard storage backends to v2 are reusing the same configuration for storage as we had in v1. Now is a good time to rethink that configuration, in particular:
  * better align with standard components of OTEL Collector. For example, the gRPC storage (https://github.com/jaegertracing/jaeger/pull/5228) is conceptually very similar to OTLP Exporter - they both send data over gRPC to a remote service. Our configuration is pretty slim, while OTLP Exporter's configuration has [a lot more features](https://github.com/open-telemetry/opentelemetry-collector/blob/6be5fe9fecd12a39adf093a2e7c5b55700bc0518/exporter/otlpexporter/config.go#L16), there is no reason why we cannot support them (would be even better if we could simply reuse OTEL's configuration utilities for gRPC)
  * our storage configs have been accumulating over time, we can see if there are better logical groupings. For example, ES config is a [flat list of everything](https://github.com/jaegertracing/jaeger/blob/ef4791ec7b0761f7a6f9ac3cace54a2039483d8e/pkg/es/config/config.go#L47), we can group many flags into sub-types so that the YAML config looks a lot more structured than using long field names like `priority_dependencies_template`
  * ensure that we have sensible defaults. For example, in #5398 basic options had to be added to Cassandra configuration, even though in v1 many of them are already defaulted to these values, so we're clearly missing defaulting mechanism. It's somewhat complicated by the fact that the storage extension cannot actually define the defaults in `CreateDefaultConfig` because at that point we don't known which storage will be used.

## Scope
  * [x] Cassandra storage config -- #5928
  * [ ] Elasticsearch / OpenSearch storage config -- #6059
  * [x] Badger storage config -- #5926
  * [x] Memory storage config -- #5923
  * [x] Kafka config -- #6027
  * [x] grpc storage (e.g. issue #6030) -- #6041
  * [x] Adaptive sampling processor / extension config -- #6021 
  * [x] Query service config -- #5996
  * [x] Collector-specific config -- #6040
  * [x] Utilize env var defaults available since OTEL v0.110 e.g. https://github.com/jaegertracing/jaeger/blob/c655e56694a5340520b330968452c8db99db27eb/cmd/jaeger/internal/integration/kafka_test.go#L24

## Tasks / outcomes
For each of the above components, we need to ensure
  * [ ] All config fields are tagged with `mapstructure` such that they can be addressable from YAML via "good" names
  * [ ] Configs implement Validate() -- [example](https://github.com/jaegertracing/jaeger/blob/edc3152254a154bdf79910872addf0aec8730e37/pkg/cassandra/config/config.go#L178)
  * [ ] Configs via YAML support the same defaults as in jaeger-v1
  * [ ] Configs reuse standard elements of OTEL configs whenever possible, e.g. TLS, clientcfg, etc. 
  * [ ] Configuration looks "logical" and properly grouped, not flattened with long weird names (good example #5790)
  * [ ] We create a migration guide document with a table that lists v1 CLI flags and the corresponding v2 config fields ([example for Kafka](https://docs.google.com/document/d/1karnc_XxGfnAHPyAP8Uf3Kun_T5xfOaktcSYqFuWoFw/edit?usp=sharing))

## How to work on this meta-issue
  * pick a component / area
  * create a dedicated ticket for it
  * copy tasks / outcomes from above
  * use the ticket for design discussions, updates, links to PRs

**Comment by mahadzaryab1** [comment]
@yurishkuro What is the status of this issue? Is there anything I can help with?

**Comment by yurishkuro** [comment]
yes, plenty. I just updated the description.

**Comment by mahadzaryab1** [comment]
@yurishkuro are the configs for v1 supposed to be in `plugin/storage/*/options.go` and the configs for v2 supposed to be in `pkg/*/config.go`?

**Comment by yurishkuro** [comment]
yes, that's accurate

**Comment by mahadzaryab1** [comment]
how come some stores still have the v2 configuration living in `plugin/storage/*`? do we want to move those over?

**Comment by yurishkuro** [comment]
We are in the transition period. Moving them doesn't solve anything, having configs side by side is actually convenient. The long term goal is to only have v2 configurations.

Wwe started v2 by just wrapping v1 configs. For some backends we did preliminary work of cleaning up and making v2 the "primary" config, i.e. the Factory uses v2 config directly, but v1 config still drives the v1 cli flags and can be transformed into v2. We could continue using this pattern.  The reason we want v2 configs to be primary is to ensure that all their settings are actually used by the storage implementation - there's less guarantee of that if v1 is primary and v2 is translated into v1.

But overall this ticket is about what v2 config look like, rather than where they are located.

**Comment by mahadzaryab1** [comment]
@yurishkuro sounds good! and where should the migration doc be created? is any public google doc fine?

**Comment by yurishkuro** [comment]
yes a google doc is fine

**Comment by mahadzaryab1** [comment]
@yurishkuro PR for memory storage component at https://github.com/jaegertracing/jaeger/pull/5925

**Comment by mahadzaryab1** [comment]
@yurishkuro PR for badger storage component at https://github.com/jaegertracing/jaeger/pull/5927

**Comment by mahadzaryab1** [comment]
@yurishkuro PR for Cassandra component ready for review at https://github.com/jaegertracing/jaeger/pull/5949.

**Comment by mahadzaryab1** [comment]
@yurishkuro PR for Query Service ready for review at https://github.com/jaegertracing/jaeger/pull/5998

**Comment by mahadzaryab1** [comment]
@yurishkuro we can link the following PRs to the issue description for badger: 
- https://github.com/jaegertracing/jaeger/pull/5927
- https://github.com/jaegertracing/jaeger/pull/5937

**Comment by mahadzaryab1** [comment]
@yurishkuro what is the `Collector-specific config` checklist item referring to?

**Comment by yurishkuro** [comment]
> what is the Collector-specific config checklist item referring to?

if you run `SPAN_STORAGE_TYPE=memory go run ./cmd/collector help` there are a bunch of collector-specific flags printed that are not related to storage but to the collector itself. Most of them are related to http/grpc endpoints, but some could control the overall collector's behavior. Ideally we need to create a gdoc mapping all these flags to the corresponding OTEL config locations and if any are not supported decide what to do about them.

**Comment by mahadzaryab1** [comment]
> > what is the Collector-specific config checklist item referring to?
> 
> 
> 
> if you run `SPAN_STORAGE_TYPE=memory go run ./cmd/collector help` there are a bunch of collector-specific flags printed that are not related to storage but to the collector itself. Most of them are related to http/grpc endpoints, but some could control the overall collector's behavior. Ideally we need to create a gdoc mapping all these flags to the corresponding OTEL config locations and if any are not supported decide what to do about them.

@yurishkuro Got it! So for this part we just need to create a migration guide? No code changes?

**Comment by yurishkuro** [comment]
Perhaps, depends on what the comparison would show.

**Comment by mahadzaryab1** [comment]
@yurishkuro Thanks! Would you also be able to help me understand how to solve `Utilize env var defaults one OTEL supports them in 0.110` ? How do we determine which things need to be defaulted? As well, where do these defaults needs to be utilized? Is it just in the docker compose setups?

**Comment by yurishkuro** [comment]
We had a number of nasty workarounds because we couldn't use defaults. For instance, Kafka e2e test needs to physically rewrite the config because we can't just have a var for encoding without default (it makes the config invalid by default). I think it's sufficient to just fix that to close the item, since we can add more vars/defaults incrementally as the needs arise.

**Comment by mahadzaryab1** [comment]
@yurishkuro we can link the following issues to the issue description as they are complete / in-review:
- https://github.com/jaegertracing/jaeger/issues/6021
- https://github.com/jaegertracing/jaeger/issues/6027

**Comment by yurishkuro** [comment]
For Kafka, we have [this document](https://docs.google.com/document/d/1karnc_XxGfnAHPyAP8Uf3Kun_T5xfOaktcSYqFuWoFw/edit#heading=h.nim4tfs7gkb0).

**Comment by mahadzaryab1** [comment]
> For Kafka, we have [this document](https://docs.google.com/document/d/1karnc_XxGfnAHPyAP8Uf3Kun_T5xfOaktcSYqFuWoFw/edit#heading=h.nim4tfs7gkb0).

@yurishkuro Did you want me to link this somewhere?

**Comment by yurishkuro** [comment]
no - I keep all links in the v2 RFC doc.

**Comment by mahadzaryab1** [comment]
@yurishkuro can link https://github.com/jaegertracing/jaeger/issues/6041 for grpc storage

**Comment by mahadzaryab1** [comment]
@yurishkuro looks like we're pretty close to finishing this issue - do you know what the status is of https://github.com/jaegertracing/jaeger/pull/5790? any help needed there?

**Comment by yurishkuro** [comment]
> do you know what the status is of [#5790](https://github.com/jaegertracing/jaeger/pull/5790)? any help needed there?

I had some comments that the author did not respond to. We can ping the author on the issue - if they don't have time to continue, we could take over that PR, it was nearly done iirc.

**Comment by JaredTan95** [comment]
> > do you know what the status is of [#5790](https://github.com/jaegertracing/jaeger/pull/5790)? any help needed there?
> 
> I had some comments that the author did not respond to. We can ping the author on the issue - if they don't have time to continue, we could take over that PR, it was nearly done iirc.

Sorry for the late reply. After @yurishkuro reivew and adjustment, I feel that the logic here is rather complicated for me. I can no longer make the changes at present, and hope to get more help from the maintainer or take over directly.

**Comment by mahadzaryab1** [comment]
> > > do you know what the status is of [#5790](https://github.com/jaegertracing/jaeger/pull/5790)? any help needed there?
> 
> > 
> 
> > I had some comments that the author did not respond to. We can ping the author on the issue - if they don't have time to continue, we could take over that PR, it was nearly done iirc.
> 
> 
> 
> Sorry for the late reply. After @yurishkuro reivew and adjustment, I feel that the logic here is rather complicated for me. I can no longer make the changes at present, and hope to get more help from the maintainer or take over directly.

@JaredTan95 no worries! I can try picking up your PR and try addressing the feedback.

**Comment by mahadzaryab1** [comment]
> > > do you know what the status is of [#5790](https://github.com/jaegertracing/jaeger/pull/5790)? any help needed there?
> > 
> > 
> > I had some comments that the author did not respond to. We can ping the author on the issue - if they don't have time to continue, we could take over that PR, it was nearly done iirc.
> 
> Sorry for the late reply. After @yurishkuro reivew and adjustment, I feel that the logic here is rather complicated for me. I can no longer make the changes at present, and hope to get more help from the maintainer or take over directly.

@JaredTan95 @yurishkuro I've opened a new PR at https://github.com/jaegertracing/jaeger/pull/6060 since I didn't have permission to modify the existing ones. I've addressed most of the feedback that was left on the original PR. Please take a look and let me know if you have any other feedback.

**Comment by mahadzaryab1** [comment]
@yurishkuro The elasticsearch configurations are now complete as well. Any other items we want to address here? Otherwise, I think we can close this issue out.

**Comment by yurishkuro** [comment]
Did you already update the google doc with the mapping?

**Comment by mahadzaryab1** [comment]
@yurishkuro Yes - the migration guide can be viewed [here](https://docs.google.com/document/d/1rabu8zvjoZeHx-HNqvK5kjsujMEBC7DkR2MYeOvB6HI/edit?tab=t.0).

**Comment by yurishkuro** [comment]
I think this is completed - huge thanks to @mahadzaryab1 🚀 , this is a critical milestone for v2.
