### ISSUE TITLE
[jaeger-v2] Align Memory Storage Config With OTEL

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#5923]
### Requirement

In this issue, we want to align the configuration for **memory storage** with OTEL (part of #5229)

### Tasks / outcomes

- [x] All config fields are tagged with mapstructure such that they can be addressable from YAML via "good" names
- [x] Configs implement Validate()
- [x] Configs via YAML support the same defaults as in jaeger-v1
- [x] Configs reuse standard elements of OTEL configs whenever possible, e.g. TLS, clientcfg, etc. (N/A)
- [x] Configuration looks "logical" and properly grouped, not flattened with long weird names
- [x] We create a migration guide document with a table that lists v1 CLI flags and the corresponding v2 config fields
