### ISSUE TITLE
[jaeger-v2] Align Kafka Config With OTEL

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6002]
### Requirement

In this issue, we want to align the configuration for kafka with OTEL (part of https://github.com/jaegertracing/jaeger/issues/5229)

### Tasks / outcomes

- [ ] All config fields are tagged with mapstructure such that they can be addressable from YAML via "good" names
- [ ] Configs implement Validate()
- [ ] Configs via YAML support the same defaults as in jaeger-v1
- [ ] Configs reuse standard elements of OTEL configs whenever possible, e.g. TLS, clientcfg, etc.
- [ ] Configuration looks "logical" and properly grouped, not flattened with long weird names
- [ ] We create a migration guide document with a table that lists v1 CLI flags and the corresponding v2 config fields

**Comment by mahadzaryab1** [comment]
We are using upstream kafka exporter and receiver from open telemetry already, so nothing needs to be done here.
