### ISSUE TITLE
[jaeger-v2] Refactor Adaptive Sampling Processor Configurations

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6021]
### Requirement

In this issue, we want to refactor the configurations for the adaptive sampling processor to ensure that the configuration is laid out logically (part of https://github.com/jaegertracing/jaeger/issues/5229)

### Tasks / outcomes

- [x] All config fields are tagged with mapstructure such that they can be addressable from YAML via "good" names
- [x] Configs implement Validate()
- [x] Configs via YAML support the same defaults as in jaeger-v1
- [x] Configs reuse standard elements of OTEL configs whenever possible, e.g. TLS, clientcfg, etc.
- [x] Configuration looks "logical" and properly grouped, not flattened with long weird names
- [x] We create a migration guide document with a table that lists v1 CLI flags and the corresponding v2 config fields

**Comment by mahadzaryab1** [comment]
@yurishkuro Do we need https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/internal/processors/adaptivesampling/config.go? It looks to be empty and all the config seems to be in the remote sampling extension?

**Comment by mahadzaryab1** [comment]
@yurishkuro is there a reason that `SamplingStore` is separate from the rest of the config in https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/internal/extension/remotesampling/config.go#L41-L46? Can I move `SamplingStore` under `adaptive.Options`?

**Comment by yurishkuro** [comment]
The reason is because it's not applicable to v1 collector.

**Comment by mahadzaryab1** [comment]
Does it hurt to combine it? Currently in the config we have something like:
```yaml
sampling_store:
sampling:
  ...
```
It would be nice to do something like
```yaml
sampling:
  store:
  ...
```

**Comment by yurishkuro** [comment]
Feel free to propose a change. 

Do we use store or storage in query service?

**Comment by mahadzaryab1** [comment]
@yurishkuro [Here](https://docs.google.com/document/d/1_gtjUP3FlFTY5Ni98fP9qN9TnGCCQnMTQuyew_xEQAc/edit?usp=sharing) is the migration guide for this processor. Are there any other action items as part of this issue? If not, we can close it out.

**Comment by mahadzaryab1** [comment]
It was decided that no changes were needed to the configuration. Only the migration guide was created as part of this issue which has been added to the V2 RFC.
