### ISSUE TITLE
Implement framework to validate backwards compatibility of metrics

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6278]
Jaeger binaries produce various metrics that can be used to monitor Jaeger itself in production, such as throughput, queue saturation, error rates, etc. We historically treated those metrics as a stable public API (we even provide a [Grafana dashboard mixin](https://github.com/jaegertracing/jaeger/tree/main/monitoring/jaeger-mixin)), but we never actually had proper integration tests that validate that changes to the code do not break the metrics.

## Proposal

We can enhance our existing integration tests to also perform comparison of the metrics. The full set of all possible metrics is never available from a single run because if some components are not utilized (e.g. adaptive sampling or a particular storage type) then their metrics will not be registered. However, since our integration tests cover most of the components, we can scape the metrics endpoint at the end of each test and combine them into a full picture.

Caveat: the exact shape of the metrics depends on all the nested namespaces that could be applied to the `metrics.Factory`, so it is sensitive to the exact code in the main functions, which is where `metrics.Factory` always originates. Our [integration tests for Jaeger v2][testsv2] usually use the actual binary, so the resulting metrics will reflect how that binary performs in production. But all [integration tests for v1][testsv1] are run from a unit testing framework and the `metrics.Factory` initialization may not match how it's done in the `main`s. So we may only be able to solve this for Jaeger v2, which is fine.

[testsv2]: https://github.com/jaegertracing/jaeger/tree/main/cmd/jaeger/internal/integration
[testsv1]: https://github.com/jaegertracing/jaeger/tree/main/plugin/storage/integration

## Approach

* At the end of each integration test (CIT) workflow we scrape the metrics collected by the binary and upload them as a github artifact
* Then the final workflow can gather all those artifacts and compare them with similar reports from the latest release. If differences are found it can upload them as another artifact and link to the PR so that maintainers can inspect the changes and decide if they are acceptable.
* The artifacts uploaded for the official release can also be referenced from the documentation website as a way of documenting the current collection of metrics.

## Help Wanted

We seek community help to implement this functionality. This is not a 30min fix, but we still marked it as `good-first-issue` because it can be done incrementally.

## Tasks

* [ ] currently all CIT workflows are independent. In order to be able to have a final job once all CIT jobs are finished we may need to combine them all into a single CIT workflow with multiple jobs
* [ ] the ability to scrape and compare metrics was implemented in #5941. We need to integrate the scraping into each CIT workflow (using a helper script) and upload the output as workflow artifacts
* [ ] implement the validation job in a workflow that would compare artifacts from the current PR with those from the latest release and generate a diff (also uploaded as a separate artifact)
* [ ] make the validation job post some form of summary as a comment to the PR (or as the output of the Check)

**Comment by Saumya40-codes** [comment]
> ## Tasks
> * [ ]  currently all CIT workflows are independent. In order to be able to have a final job once all CIT jobs are finished we may need to combine them all into a single CIT workflow with multiple jobs

Instead of this, can we use [upload artifact action](https://github.com/actions/upload-artifact)  and a single file of [download artifact action](https://github.com/actions/download-artifact)

So, we have one main file to get artifacts from all workflow runs which might look something like this:
```
name: Get All Artifact

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflow_1:
    uses: ./.github/workflows/workflow-1.yml

  workflow_2:
    uses: ./.github/workflows/workflow-2.yml

  deploy:
    runs-on: ubuntu-latest
    needs:
      - workflow_1
      - workflow_2
    steps:
      - name:  Checkout
        uses: actions/checkout@v3

      - name: Download artifact from workflow-1.yml
        uses: actions/download-artifact@v4
        with:
          name: 'metrics-1'
          path: 'deploy'

      - name: Download artifact from workflow-2.yml
        uses: actions/download-artifact@v4
        with:
          name: 'metrics-2'
          path: 'deploy'

      # we will be doing comparison here with the binary

      - name: 'Log the content of metrics-1.txt (from compile.yml)'
        run: |
          cat deploy/metrics-1.txt

      - name: 'Log the content of hello-2.txt (from compile-2.yml)'
        run: |
          cat deploy/metrics-2.txt
```

i was able to work through this 
![Image](https://github.com/user-attachments/assets/ef6187f7-da46-4c6b-a469-a799f7454520)

**Comment by yurishkuro** [comment]
> Instead of this, can we use [upload artifact action](https://github.com/actions/upload-artifact) and a single file of [download artifact action](https://github.com/actions/download-artifact)

why is it "instead"? The point of the task was to merge all different workflows as different jobs in a single workflow. It's fine to keep them as separate included files (only if you keep them in the workflows dir they may still get executed separately, I don't think your `uses:` syntax works for workflows)

**Comment by vaidikcode** [comment]
Hi, @yurishkuro. I wanted to know what specific tasks we want the helper script to perform in task 2?

**Comment by yurishkuro** [comment]
it need to get all metrics available from Jaeger binary at the end of the e2e test run and upload them as a workflow artifact. This will already allow us inspecting what the metrics look like. Then the next step would be to compare those metrics with those from the latest release.

**Comment by vaidikcode** [comment]
Hi @yurishkuro, Could you clarify how we plan to retrieve the metrics in the CI/CD environment? Your guidance on this would be greatly appreciated.

Thanks!

**Comment by yurishkuro** [comment]
@vaidikcode aftet a given e2e test is finished we can curl the metrics endpoint (usually on :8888) to get all metrics, while the binary is still running.

**Comment by frittentheke** [comment]
An e2e test also needs to take the dynamics into account:
* dynamically registered metrics
* the actual values changing to >0 (an increment happening, not just the initialization of the metric), see e.g. https://github.com/jaegertracing/jaeger/issues/7125

**Comment by pipiland2612** [comment]
Hi @yurishkuro, is this issue still relevant now ? If yes, what task now is left to do ? I think I can invest time into this issue. Thanks!

**Comment by yurishkuro** [comment]
Yes, we had a number of regressions in metrics in the past year, despite having some automation to compare metrics.

**Comment by neoandmatrix** [comment]
Hi, @yurishkuro is only the 
> implement a way to incorporate the metrics report into documentation website

part left in this issue? i was planning to give this a try if this is still rellevant.

Thanks.

**Comment by neoandmatrix** [comment]
Hi @yurishkuro , can you please once confirm that what i have concluded in above comment is correct or not?
Thanks.

**Comment by pipiland2612** [comment]
Hi @neoandmatrix, I can confirm that the only part left is the last task, not sure about whether it is still relevant. You can ask on jaeger slack though

**Comment by neoandmatrix** [comment]
Thanks @pipiland2612

**Comment by Amaan729** [comment]
Hi! I'd like to work on this. I've opened a draft PR (#8204) implementing the verify-metrics-snapshot composite action — it scrapes /metrics after integration tests, uploads a snapshot artifact, and diffs metric names against a committed baseline to catch removals. Happy to iterate based on feedback before marking it ready for review.

**Comment by abhay1999** [comment]
I see most of the tasks are done — the scraping, comparison, and PR summary comment are all in place. The remaining piece is integrating the metrics report into the documentation website.

Looking at the current setup, the workflow already uploads artifacts and posts a summary. For the docs integration, would the approach be something like:
- Add a step in the release workflow that downloads the combined metrics artifact
- Runs a script to convert it to Markdown/HTML
- Commits it to the `jaegertracing.io` docs repo (or a dedicated section in this repo's docs)

Is there a preferred docs pipeline already in use for generated content, or would this be a new pattern? Happy to work on this last milestone.

**Comment by Amaan729** [comment]
Thanks for the detailed breakdown, @abhay1999! That makes the remaining scope very clear.
For the docs integration piece — I took a quick look at the repo and didn't spot an existing pattern for committing generated content to the docs site from a release workflow. A few clarifying questions before I proceed:

1. Is the target the jaegertracing/documentation repo, or a /docs section within this repo?
2. Is Markdown preferred over HTML for the generated report (given the existing docs use .md files)?
3. For the release workflow step, should this run on every release tag, or only on stable (non-RC) releases?

Happy to draft the release workflow step and conversion script once I have direction on the above. I can open it as a follow-up PR on top of #8204.

**Comment by balgaly** [comment]
Happy to work on this — plan to add a metrics snapshot comparison to the existing integration tests and wire up a golden-file check. Will open a draft PR to discuss approach if needed.

**Comment by yurishkuro** [comment]
I updated the issue with suggestion on how to implement the docs item

**Comment by Amaan729** [comment]
Thanks @yurishkuro — the CLI flags example makes the approach very clear. I'll follow the same pattern: download the combined metrics artifact from the release workflow, write it to a YAML data file in the jaegertracing/documentation repo, and let the existing template infrastructure render it. I'll open a follow-up PR on top of #8204 implementing this.

**Comment by Atharv3221** [comment]
I am working on this
