### ISSUE TITLE
Implement adjusters to operate on OTLP data format

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6344]
Today, we have adjusters in `model/adjuster` that perform modifications to a trace object. We want to implement v2 versions of all these adjusters that operate directly on the OTLP data format (`ptrace.traces` instead of on `model.Trace`). 
- [x] Bad Span References - #6354
- [x] Clockskew -#6392
- [x] IP Tag - #6355
- [x] OTEL Tag - #6358
- [x] Parent Reference - not required due to https://github.com/jaegertracing/jaeger/issues/6344#issuecomment-2542569537
- [x] Sort Tag And Log Fields - #6389 
- [x] Span Hash Deduper - #6391
- [x] Zipkin Span ID Uniquify - #6367
- [x] Add warnings as attributes
- [x] Update OTLP->Model Translation to add warnings(https://github.com/jaegertracing/jaeger/pull/6358#discussion_r1885402856)
  - [x] ProtoFromTraces - https://github.com/jaegertracing/jaeger/pull/6394
  - [x] ProtoToTraces - https://github.com/jaegertracing/jaeger/pull/6397
- [x] Add function for getting standard adjusters - https://github.com/jaegertracing/jaeger/pull/6396

**Comment by mahadzaryab1** [comment]
The parent reference adjuster is not needed when operating on the OTLP data model because because the parent span ID is recorded explicitly on the span instead of a reference (or a link in OTLP terminology).

**Comment by yurishkuro** [comment]
Some adjusters cannot be implemented in OTLP in the same way. For example, pdata.Traces has no place to store warnings, and the sorting adjuster won't work because pdata uses maps internally for attributes. Given that the UI isn't going to accept OTLP anytime soon, even if the internals and APIs like APIv3 all support OTLP we would still need a transformation into UI JSON data model, which is easiest to achieve today with  `OTLP -> model -> uijson`. It means that whichever adjusters we are not fully able to do in the OTLP layer would need to be injected into `OTLP -> model`. I would suggest we replace all instances of `OTLP -> model` conversions we might have in the code with a call to a helper function in the `jotlp` package (which on reflection we should rename jpdata).

**Comment by yurishkuro** [comment]
Also, we might already have some data loss in the `factoryadapter.TraceReader` because storage backends are expected to store span warnings that might be produced by inbound sanitizers.

**Comment by mahadzaryab1** [comment]
> Also, we might already have some data loss in the `factoryadapter.TraceReader` because storage backends are expected to store span warnings that might be produced by inbound sanitizers.

@yurishkuro I don't follow this point. Would you be able to elaborate? How do we have data loss?

**Comment by yurishkuro** [comment]
> How do we have data loss?

Suppose we utilize Span.Warnings on the ingestion path. It gets stored in the database, and then v1 reader re-inflates it back into Span.Warnings. But then when we wrap that reader into adapter reader, we call model2pdata from OTEL, which may ignore Span.Warnings and they get lost. We can check how that transform is implemented and perhaps fix it to use the same `jaeger.internal.warnings` attribute when translating from the model.

**Comment by mahadzaryab1** [comment]
> > How do we have data loss?
> 
> Suppose we utilize Span.Warnings on the ingestion path. It gets stored in the database, and then v1 reader re-inflates it back into Span.Warnings. But then when we wrap that reader into adapter reader, we call model2pdata from OTEL, which may ignore Span.Warnings and they get lost. We can check how that transform is implemented and perhaps fix it to use the same `jaeger.internal.warnings` attribute when translating from the model.

Got it. We can fix this by adding a wrapper around the translator in jptrace like you suggested.

**Comment by mahadzaryab1** [comment]
All adjusters have been migrated and the development of the query service is now unblocked
