### ISSUE TITLE
[tracking issue] Ability to trace web apps

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#723]
Currently Jaeger does not directly support starting traces from the web browsers, although it is theoretically possible by using zipkin-js client (however it would force the rest of the services into zipkin's B3 headers).

The following is required:

* [ ] Jaeger client for Javascript (https://github.com/jaegertracing/jaeger-client-javascript/issues/1)
* [ ] Define canonical JSON model #706 (depends on #773)
* [ ] Jaeger collector to be able to accept Jaeger spans in JSON format (depends on #706)
* [ ] Example / documentation

The user application that would serve the Web app would either need to set up CORS headers to allow Jaeger client to submit traces to a different address, or to proxy those submissions to Jaeger collector.

**Comment by pavolloffay** [comment]
Closing this as we are not planning to work on client libraries anymore. This functionality should be available in OpenTelemetry collector.
