### ISSUE TITLE
Replace "good commit message" guidelines across all repos

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#771]
Apply this change #770 to all other Jaeger repos:

* [x] documentation
* [x] jaeger-client-cpp
* [x] jaeger-client-csharp
* [x] jaeger-client-go
* [x] jaeger-client-java
* [x] jaeger-client-javascript
* [x] jaeger-client-node
* [x] jaeger-client-python
* [x] jaeger-idl
* [x] jaeger-kubernetes
* [x] jaeger-lib
* [ ] jaeger-openshift
* [ ] jaeger-performance
* [x] jaeger-ui
* [x] legacy-client-java
* [ ] spark-dependencies
* [ ] xdock-zipkin-brave

**Comment by B0go** [comment]
@yurishkuro you can check **jaeger-kubernetes** as of https://github.com/jaegertracing/jaeger-kubernetes/pull/83

**Comment by PikBot** [comment]
@yurishkuro jaeger-client-javascript does not have CONTRIBUTING.md. Is this something that needs to be added as well?

**Comment by kevinearls** [comment]
Sure, I can take care of those within the next couple of days.

**Comment by pavolloffay** [comment]
I think I am late for the party but I would like more to have one main contributing.md here in main repo and just reference it in other repositories.

**Comment by yurishkuro** [comment]
I was thinking about that as well. There are some variations by language but they should be easy to consolidate. We sometimes also add "developing" help into Contributing.md, those need to be factored out somehow.

**Comment by yurishkuro** [comment]
@PikBot that would be great. I'd suggest a quick look around existing CONTRIBUTING files first to see what kind of deviations we have in them, including possible wording like "in this repository", which won't work in a consolidated document.

**Comment by PikBot** [comment]
### **Generalized CONTRIBUTING.md:**
1. Making a change
2. License and Certificate of Origin 
3. Sign your work 

### **Repos with Specific sections:** 
**“Getting started”**
1. jaeger-client-csharp

 
**“Getting started” & “Import Groupings”**
1. jaeger-lib
2. jaeger-client-go


**“Developing”**
1. legacy-client-java
2. jaeger-client-java
3.  jaeger-client-node
4. jaeger-client-python

@yurishkuro with the information above, maybe we can have language specific contribution details in the main CONTRIBUTING.md? But the file might become too crowded.

**Comment by yurishkuro** [comment]
I'm conflicted about how best to proceed. @pavolloffay  what were your thoughts on repo-specific sections?

**Comment by jpkrohling** [comment]
How about having the other way around: the main repo's `CONTRIBUTING.md` serves as a reference to every other `CONTRIBUTING.md`? Like:

`jaegertracing/jaeger/CONTRIBUTING.md`:
1. Making a change
1. License and Certificate of Origin
1. Sign your work

`jaegertracing/jaeger-client-java/CONTRIBUTING.md`:
1. This guide extends the main one at [jaegertracing/jaeger/CONTRIBUTING.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md)
1. Developing

If we don't want to repeat things from `jaeger-client-java` across other client repositories, they could say something similar:

`jaegertracing/jaeger-client-python/CONTRIBUTING.md`:
1. Refer to the [Jaeger Client Java's CONTRIBUTING.md](https://github.com/jaegertracing/jaeger-client-java/blob/master/CONTRIBUTING.md) for general information about contributing to a Jaeger client library
1. pip, virtualenv, ...

**Comment by pavolloffay** [comment]
> How about having the other way around: the main repo's CONTRIBUTING.md serves as a reference to every other CONTRIBUTING.md? Like: 

This is exactly what I mean. Put the general stuff in this repo
* license
* cdo
* Sign your work
* nice commit messages

and reference it in other repositories. Other repos should contain guidelines/pitfalls specific for that repo.

**Comment by jpkrohling** [comment]
Sorry, that happens when I read only the most recent comments :)

**Comment by yurishkuro** [comment]
My question is about structuring the individual MDs. If we look at Java client https://github.com/jaegertracing/jaeger-client-java/blob/master/CONTRIBUTING.md,  the first 7 lines are not specific to Java, they are general "greetings, glad you want to help". Then goes Java specific part "Developing". Then again goes the generic part about the policies. This pattern probably exists in all repos.

**Comment by PikkaPikkachu** [comment]
For individual MDs, we could possibly use the following template: 

## How to Contribute to Jaeger
Refer here : _[Link to General CONTRIBUTING.md]_

### [Insert Specific Section I]
_Description_

### [Insert Specific Section II]
_Description_

.
.
.

**Comment by PikBot** [comment]
For individual MDs, we could possibly use the following template: 

## How to Contribute to Jaeger
Refer here : _[Link to General CONTRIBUTING.md]_

### [Insert Specific Section I]
_Description_

### [Insert Specific Section II]
_Description_

.
.
.

**Comment by PikBot** [comment]
@yurishkuro, I agree that the intro should be more welcoming, that was just a very rough sample of the template! Maybe we could have the intro same as that of documentation/CONTRIBUTING.md, but with the word "document" linked to the general CONTRIBUTING.md, like so: 

_We'd love your help!_

_Jaeger is Apache 2.0 licensed and accepts contributions via GitHub pull requests. This [document] (./Link-to-General-CONTRIBUTING.md) outlines some of the conventions..._

**Comment by yurishkuro** [comment]
Sgtm. It may be better to move the shared part into a separate document altogether, eg CONTRIBUTING_GUIDELINES.md, that way we can start just in the main repo with the new pattern.

**Comment by preslavmihaylov** [comment]
We can mark jaeger-client-javascript as resolved after #6
