### ISSUE TITLE
Stop testing tchannel in crossdock

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#783]
The tchannel repos already have OpenTracing crossdock tests. Having them in Jaeger repos as well is legacy code, and it creates unnecessary conflicts, eg in the Go client we are stuck with the old version of thrift, the Node client is not able to run the full test matrix, etc.

Plan to remove tchannel from crossdock is:
  - [x] remove it from all docker-compose files  first
  - [x] remove code from the driver
  - [ ] remove code from clients
    - [x] go
    - [x] java
    - [ ] node
    - [ ] python

**Comment by isaachier** [comment]
👍

**Comment by pavolloffay** [comment]
It seems it have been fixed in all linked repositories. I will close this.
