### ISSUE TITLE
Create issue and pull request templates

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#785]
Apply this change https://github.com/jaegertracing/jaeger-client-go/pull/289 to all repositories.

* [x] documentation
* [x] jaeger
* [x] jaeger-client-cpp
* [x] jaeger-client-csharp
* [x] jaeger-client-go
* [x] jaeger-client-java
* [x] jaeger-client-javascript
* [x] jaeger-client-node
* [x] jaeger-client-python
* [x] jaeger-idl
* [x] jaeger-kubernetes
* [x] jaeger-lib
* [x] jaeger-openshift
* [x] jaeger-performance
* [ ] jaeger-ui
* [x] legacy-client-java
* [x] spark-dependencies
* [x] xdock-zipkin-brave

**Comment by yurishkuro** [comment]
@PikBot thanks a ton for your help with all these changes!  I left the UI issue open for @tiffon to look at, since it changes the existing template, but everything else is done, so I am going to close this ticket. Once again, many thanks!

**Comment by PikBot** [comment]
@yurishkuro happy to help! Please let me know if there is anything else I can help with.
