### ISSUE TITLE
Support W3C Trace Context headers

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#855]
https://github.com/w3c/distributed-tracing

* [ ] Go client
* [x] Java client https://github.com/jaegertracing/jaeger-client-java/pull/694
* [ ] Node client
* [ ] Python client https://github.com/jaegertracing/jaeger-client-python/issues/284
* [ ] C++ client https://github.com/jaegertracing/jaeger-client-cpp/issues/160
* [ ] C# client https://github.com/jaegertracing/jaeger-client-csharp/issues/90

**Comment by trevnet** [comment]
+1 waiting on this so I can use jaeger for my services

**Comment by grounded042** [comment]
@yurishkuro are we also wanting to support the correlation context headers defined in that repo or just the trace context headers?

**Comment by yurishkuro** [comment]
Correlation header is currently not finalized as people have disagreements. So I would skip it for now. It means that we still need another way of propagating the baggage.

**Comment by grounded042** [comment]
so when we add Jaeger baggage in as long as the other Jaeger clients implement the same propagation method for baggage for W3C we'll be good, but until they finalize the correlation header technically no one else will be able to use that baggage. I'm fine with that - we just have to make sure all the Jaeger clients implement baggage handling for W3C the same.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients. OpenTelemetry already supports W3C.
