### ISSUE TITLE
Support 128bit trace IDs

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#858]
Currently Jaeger clients generate 64bit trace IDs by default. Organizations with large traffic volume may run into ID collision and need 128bit trace IDs (also required by w3c trace context #855). Jaeger backend and some clients already support 128bit IDs. This issue is to track support across all clients.

## Requirements 

* By default the clients must still generate 64bit IDs, to maintain compatibility with existing code in production, especially in the applications that have not yet upgraded to the newer clients. 
* 128bit IDs for new traces must be opt-in via tracer configuration.
* However, if a client receives 128bit trace IDs, it should propagate it further as is, without truncating to 64bit. The risk of receiving side not being able to parse it is an organizational challenge (below).

## Work tracker

* [x] Go client
* [x] Java client (https://github.com/jaegertracing/jaeger-client-java/issues/495)
* [x] Python client (https://github.com/jaegertracing/jaeger-client-python/issues/228)
* [x] Javascript/Node.js client (https://github.com/jaegertracing/jaeger-client-node/issues/295)
* [x] C# client
* [x] C++ client
* [x] Update clients feature matrix in the documentation

## Org Upgrade Process

The proposal for organizations wishing to upgrade to 128bit IDs is to follow this process:
  1. make sure that all applications / services are upgraded to use Jaeger clients that can *read* 128bit IDs, but on trace creation still generate 64bit.
  1. once all applications are upgraded, start rolling out a configuration change that instructs Jaeger clients to generate 128bit IDs for new traces.

**Comment by isaachier** [comment]
Don't forget C++, although this is already done.

**Comment by yurishkuro** [comment]
Does C++ implementation meet the requirements above?

**Comment by isaachier** [comment]
Ya this "feature" ended up delaying the initial release of the C++ client because it would generate 128 bit by default. After debugging that, I added the option to generate 128 bit trace IDs, but set it off by default. The propagation inherently works because I didn't add any other logic to support 64 bit trace IDs (no truncating, etc.).

Must use option flags to use `high` bits: https://github.com/jaegertracing/jaeger-client-cpp/blob/master/src/jaegertracing/Tracer.cpp#L77-L79.

**Comment by Falco20019** [comment]
C# Version will create new 64 bit trace ids stating v0.1.1 and accept 64 and 128 bit trace ids. v0.2.0 will add configurability. We will have a look at how C++ solved it and check if that’s a solution we also want to use.

**Comment by Falco20019** [comment]
Just added configurability in https://github.com/jaegertracing/jaeger-client-csharp/pull/94 by proposing the following changes to the API:

- Added environment variable `JAEGER_TRACEID_128BIT`
- Added `WithTraceId128Bit` method to `Configuration`
- Added `WithTraceId128Bit` method to `Tracer.Builder`
- Adde `UseTraceId128Bit` property to `Tracer`

`Go` and `C++` have done it through their `options` context and do not offer it through `Configuration` (either code or environment) yet. It would be great to discuss if we like to have this in configuration and if, what env-var to use.

**Comment by yurishkuro** [comment]
I guess we should think about the objective here. Many tracing systems today do 128bit+ IDs by default. I would like Jaeger, in the future, to also default to 128bit, and make the 64it configuration a legacy thing. Given that, should it really be controlled via Configuration class, rather than more verbose/explicit tracer builder?

**Comment by isaachier** [comment]
I guess I don't mind either way. The issue with the Go/C++ client is that the default is 64 bits and any change to those options might be considered a breaking API change. C# had no option until now, so it should probably hide the option a little better, but defaulting to 64 bit is a requirement until all clients have this support. My crossdock tests broke when I tried to default to 128 bits in C++ because the Python/Java clients did not preserve the trace ID from C++ and effectively dropped the first 64 bits.

**Comment by yurishkuro** [comment]
> but defaulting to 64 bit is a requirement

Actually, when we create brand new clients it does not have to be. But we we have users already then yes.

**Comment by Tanejaankush** [comment]
> Just added configurability in [jaegertracing/jaeger-client-csharp#94](https://github.com/jaegertracing/jaeger-client-csharp/pull/94) by proposing the following changes to the API:
> 
> * Added environment variable `JAEGER_TRACEID_128BIT`
> * Added `WithTraceId128Bit` method to `Configuration`
> * Added `WithTraceId128Bit` method to `Tracer.Builder`
> * Adde `UseTraceId128Bit` property to `Tracer`
> 
> `Go` and `C++` have done it through their `options` context and do not offer it through `Configuration` (either code or environment) yet. It would be great to discuss if we like to have this in configuration and if, what env-var to use.

Hey I am using "JAEGER_TRACEID_128BIT" environment variable to enable 128bit trace id support but while I deploy application image in windows container it works fine but when I deploy the same image in kubernetes it never generates 128bit traceid for the same image and with same variables passed.

**Below is my JAEGER client configuration of c# :**

```
services.AddOpenTracing();

            // Adds the JAEGER Tracer.
            services.AddSingleton<ITracer>(serviceProvider =>
            {
                Tracer tracer = null;
                Jaeger.Configuration jaegerConfig = null;
                var hostingEnv = serviceProvider.GetRequiredService<IHostingEnvironment>();

                // Add project name as service name as a default to JAEGER client if not passed from outside as a parameter.
                serviceName = serviceName ?? hostingEnv.ApplicationName;
                try
                {
                    jaegerConfig = hostingEnv.IsDevelopment()
                        ? new Jaeger.Configuration(serviceName, loggerFactory)
                        : Jaeger.Configuration.FromEnv(loggerFactory);
                }
                catch (Exception)
                {
                    jaegerConfig = new Jaeger.Configuration(serviceName, loggerFactory);
                }

                // Get tracer instance with configurations.
                tracer = (Tracer)jaegerConfig
                    .WithSampler(Jaeger.Configuration.SamplerConfiguration.FromEnv(loggerFactory)) // This will fetch all the configurations for Sampler from environment variables.
                    .WithReporter(Jaeger.Configuration.ReporterConfiguration.FromEnv(loggerFactory)) // This will fetch all the configurations for Reporter from environment variables.
                    .GetTracer();

                // Allows code that can't use DI to also access the tracer.
                GlobalTracer.Register(tracer);

                return tracer;
            });
```

And below are the variables used to deploy image in both environments windows container and kubernetes - 


`docker run --rm --link jaeger_local --env JAEGER_SERVICE_NAME="facility.default" --env JAEGER_AGENT_HOST=jaeger_local --env JAEGER_AGENT_PORT=6831 --env JAEGER_SAMPLER_TYPE=const --env JAEGER_SAMPLER_PARAM="1" --env JAEGER_TRACEID_128BIT=true --env JAEGER_REPORTER_LOG_SPANS=true -p 1561:80 facility`

**Comment by jpkrohling** [comment]
@Tanejaankush looks like this might be related to the C# client? Could you please open an issue against that repo? https://github.com/jaegertracing/jaeger-client-csharp

**Comment by Tanejaankush** [comment]
> @Tanejaankush looks like this might be related to the C# client? Could you please open an issue against that repo? https://github.com/jaegertracing/jaeger-client-csharp

Okay raised [https://github.com/jaegertracing/jaeger-client-csharp/issues/143](url)
