### ISSUE TITLE
Version 1.6 countdown

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#919]
I would like to include the following PRs before we release 1.6:

* [x] Include HotROD binary in the distributions #917 
* [x] Improve HotROD demo #915
* [x] Package static assets inside the query-service binary #918
* [x] Update Dockerfiles to reference executable via ENTRYPOINT #815 
* [x] ES 6.x index race condition https://github.com/jaegertracing/jaeger/pull/921

**Comment by yurishkuro** [comment]
The deploy step failed, looking into it.

**Comment by yurishkuro** [comment]
Uploaded binaries manually. The Docker images were published successfully already.

Fix for depoy step: #926
