### ISSUE TITLE
Kafka Ingester

### ISSUE THREAD

**Issue by davit-y** [jaegertracing/jaeger#929]
## Requirement - what kind of business use case are you trying to solve?
 
An Ingester allows users to queue spans in Kafka instead of writing directly to storage in Collector. The Ingester consumes spans from a configurable Kafka topic and writes to any number of desired storage types. 

## Problem - what in Jaeger blocks you from solving the requirement?

This kind of queueing functionality will be new to Jaeger.

## Checklist

- [x] Initial code #940 
- [x] Split Kafka config into Producer/Consumer #957 
- [x] Changes to consumer #942 
- [x] Changes to processor #944
- [x] Create builder, flags, main #952 
- [x] Integration test #968 
- [x] Docker image https://github.com/jaegertracing/jaeger/pull/1086
- [x] Pre-built binary https://github.com/jaegertracing/jaeger/issues/1031
- [ ] Docs / instructions / examples how to run https://github.com/jaegertracing/jaeger/issues/1030

**Comment by yurishkuro** [comment]
We should also be able to specify the format of the spans, to allow us to accept Zipkin spans.

**Comment by yurishkuro** [comment]
Are we planning to support multiple writers in the ingester? If so, you may need to address separate Kafka reader/writer configurability. Is there a plan how it will be done?

**Comment by davit-y** [comment]
Yes, we will support multiple writers. The configuration for the writers will use the current storage factory configuration flags. For the consumer we will have separate Kafka/consumer options (Brokers,Topic,GroupID,Parallelism) similar to the CollectorOptions.

**Comment by yurishkuro** [comment]
I added a couple more tasks

**Comment by yurishkuro** [comment]
I created https://hub.docker.com/r/jaegertracing/jaeger-ingester/

**Comment by Dieterbe** [comment]
Hello,
this sounds interesting to me. Since we are looking to process spans with some custom logic and analyze traces to generate reports.
I know we could probably already do something like this using flink, but we're new to that, whereas we're quite familiar with kafka.

so what's the status of this?

**Comment by black-adder** [comment]
If all you care about is reading spans from kafka directly, you can configure the collector to dual write to cassandra and kafka. We need to cut a new release to enable that feature but it should already be available in master.

**Comment by pavolloffay** [comment]
The last missing part is documentation. Which is tracked separately #1030

**Comment by vprithvi** [comment]
In the current setup, `jaeger-collector` sends spans to Kafka
